language: python

matrix:
  include:
  - os: linux
    dist: xenial
  - os: linux
    dist: bionic
  - os: osx
  # - os: windows

addons:
  apt:
    packages:
    - clang
    - clang-format
    - clang-tidy
    - uncrustify
    - cppcheck
  homebrew:
    packages:
    - llvm
    - oclint
    - uncrustify
    - cppcheck
# Windows does not yet support Python
branches:
  only:
  - python
install:
- pip3 install -r requirements.txt
script: "./tests/run_tests"
